version: '2.1'

services:
  eureka-server:
    build: eureka-server/
    mem_limit: 512m
    ports:
      - 8761:8761
    networks:
      - backend

  config-service:
    build: config-service/
    mem_limit: 512m
    ports:
      - 8888:8888
    depends_on:
      - eureka-server
    networks:
      - backend

  keycloak-server:
    image: quay.io/keycloak/keycloak:26.1.4
    mem_limit: 512m
    ports:
      - 8087:8080
    volumes:
      - keycloak_data:/opt/keycloak/data
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    command: start-dev
    networks:
      - backend

  api-gateway:
    build: api-gateway/
    mem_limit: 512m
    ports:
      - 8085:8085
    depends_on:
      - config-service
      - eureka-server
    networks:
      - backend

  users-service:
    build: users-service/
    mem_limit: 512m
    ports:
      - 8082:8080
    depends_on:
      - config-service
      - eureka-server
    networks:
      - backend

  keycloak-service:
    build: keycloak-service/
    mem_limit: 512m
    ports:
      - 8081:8080
    networks:
      - backend

  cards-service:
    build: cards-service/
    mem_limit: 512m
    ports:
      - 8084:8080
    depends_on:
      - config-service
      - eureka-server
    networks:
      - backend

  activities-service:
    build: activities-service/
    mem_limit: 512m
    ports:
      - 8086:8080
    depends_on:
      - config-service
      - eureka-server
    networks:
      - backend

  accounts-service:
    build: accounts-service/
    mem_limit: 512m
    ports:
      - 8083:8080
    depends_on:
      - config-service
      - eureka-server
    networks:
      - backend

networks:
  backend:

volumes:
  keycloak_data:
    external: true
