spring:
  application:
    name: api-gateway
  config:
    import: configserver:http://localhost:8888

#CONFIG SERVER

#server:
#  port: 8085
#
#spring:
#  application:
#    name: api-gateway
#  main:
#    allow-bean-definition-overriding: true
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8080/
#  cloud:
#    gateway:
#      default-filters:
#        - TokenRelay
#      routes:
#        - id: authService
#          uri: lb://keycloak-service
#          predicates:
#            - Path=/api/auth/**
#        - id: usersService
#          uri: lb://users-service
#          predicates:
#            - Path=/api/users/**
#        - id: accountService
#          uri: lb://accounts-service
#          predicates:
#            - Path=/api/accounts/**
#        - id: cardsService
#          uri: lb://cards-service
#          predicates:
#            - Path=/api/cards/**
#        - id: activitiesService
#          uri: lb://activities-service
#          predicates:
#            - Path=/api/activities/**
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#    register-with-eureka: true
#    fetch-registry: true
#  instance:
#    prefer-ip-address: true
#



